package domain

const (
	ErrCodeDataNotFound    ErrorCode = "CORE_0001"
	ErrCodeConflictingData ErrorCode = "CORE_0002"
	ErrCodeInvalidData     ErrorCode = "CORE_0003"
	ErrCodeUnauthorized    ErrorCode = "CORE_0004"
	ErrCodeForbidden       ErrorCode = "CORE_0005"

	ErrCodeUserNil              ErrorCode = "USR_0001"
	ErrCodeUserNameEmpty        ErrorCode = "USR_0002"
	ErrCodeUserEmailEmpty       ErrorCode = "USR_0003"
	ErrCodeUserEmailInvalid     ErrorCode = "USR_0004"
	ErrCodeUserPasswordEmpty    ErrorCode = "USR_0005"
	ErrCodeUserAlreadyExists    ErrorCode = "USR_0006"
	ErrCodeUserEmailLookupError ErrorCode = "USR_0007"
	ErrCodeUserNotFound         ErrorCode = "USR_0008"
	ErrCodeUserRoleEmpty        ErrorCode = "USR_0009"

	ErrCodeOwnerNil                 ErrorCode = "OWN_0001"
	ErrCodeOwnerNameEmpty           ErrorCode = "OWN_0002"
	ErrCodeOwnerDocumentNumberEmpty ErrorCode = "OWN_0003"
	ErrCodeOwnerAlreadyExists       ErrorCode = "OWN_0004"
	ErrCodeOwnerDocumentLookupError ErrorCode = "OWN_0005"
	ErrCodeOwnerNotFound            ErrorCode = "OWN_0006"
	ErrCodeOwnerInvalidEmail        ErrorCode = "OWN_0007"
	ErrCodeOwnerUpdateValidation    ErrorCode = "OWN_0008"

	ErrCodeTenantNil                 ErrorCode = "TEN_0001"
	ErrCodeTenantNameEmpty           ErrorCode = "TEN_0002"
	ErrCodeTenantDocumentNumberEmpty ErrorCode = "TEN_0003"
	ErrCodeTenantAlreadyExists       ErrorCode = "TEN_0004"
	ErrCodeTenantDocumentLookupError ErrorCode = "TEN_0005"
	ErrCodeTenantNotFound            ErrorCode = "TEN_0006"
	ErrCodeTenantInvalidEmail        ErrorCode = "TEN_0007"

	ErrCodePropertyNil             ErrorCode = "PRO_0001"
	ErrCodePropertyOwnerIDEmpty    ErrorCode = "PRO_0002"
	ErrCodePropertyTypeIDEmpty     ErrorCode = "PRO_0003"
	ErrCodePropertyStatusIDEmpty   ErrorCode = "PRO_0004"
	ErrCodePropertyCountryIDEmpty  ErrorCode = "PRO_0005"
	ErrCodePropertyStateIDEmpty    ErrorCode = "PRO_0006"
	ErrCodePropertyCodeEmpty       ErrorCode = "PRO_0007"
	ErrCodePropertyTitleEmpty      ErrorCode = "PRO_0008"
	ErrCodePropertyStreetEmpty     ErrorCode = "PRO_0009"
	ErrCodePropertyCityEmpty       ErrorCode = "PRO_0010"
	ErrCodePropertyAlreadyExists   ErrorCode = "PRO_0011"
	ErrCodePropertyCodeLookupError ErrorCode = "PRO_0012"
	ErrCodePropertyNotFound        ErrorCode = "PRO_0013"

	ErrCodeRentalContractNil                            ErrorCode = "RCO_0001"
	ErrCodeRentalContractPropertyIDEmpty                ErrorCode = "RCO_0002"
	ErrCodeRentalContractTenantIDEmpty                  ErrorCode = "RCO_0003"
	ErrCodeRentalContractStatusIDEmpty                  ErrorCode = "RCO_0004"
	ErrCodeRentalContractStartDateEmpty                 ErrorCode = "RCO_0005"
	ErrCodeRentalContractEndDateEmpty                   ErrorCode = "RCO_0006"
	ErrCodeRentalContractInvalidDateRange               ErrorCode = "RCO_0007"
	ErrCodeRentalContractMonthlyAmountInvalid           ErrorCode = "RCO_0008"
	ErrCodeRentalContractCurrencyEmpty                  ErrorCode = "RCO_0009"
	ErrCodeRentalContractAlreadyExists                  ErrorCode = "RCO_0010"
	ErrCodeRentalContractNotFound                       ErrorCode = "RCO_0011"
	ErrCodeRentalContractActiveLookupError              ErrorCode = "RCO_0012"
	ErrCodeRentalContractInterestCalculationTypeIDEmpty ErrorCode = "RCO_0013"
	ErrCodeRentalContractAdjustmentTypeIDEmpty          ErrorCode = "RCO_0014"
	ErrCodeRentalContractDepositAmountInvalid           ErrorCode = "RCO_0015"
	ErrCodeRentalContractDueDayInvalid                  ErrorCode = "RCO_0016"
	ErrCodeRentalContractDailyInterestPercentageInvalid ErrorCode = "RCO_0017"
	ErrCodeRentalContractAdjustmentFrequencyInvalid     ErrorCode = "RCO_0018"
	ErrCodeRentalContractTotalPaymentsInvalid           ErrorCode = "RCO_0019"

	ErrCodeRentPaymentNil                   ErrorCode = "RPA_0001"
	ErrCodeRentPaymentContractIDEmpty       ErrorCode = "RPA_0002"
	ErrCodeRentPaymentPeriodEmpty           ErrorCode = "RPA_0003"
	ErrCodeRentPaymentDueDateEmpty          ErrorCode = "RPA_0004"
	ErrCodeRentPaymentBaseAmountInvalid     ErrorCode = "RPA_0005"
	ErrCodeRentPaymentTotalAmountInvalid    ErrorCode = "RPA_0006"
	ErrCodeRentPaymentPaidAmountInvalid     ErrorCode = "RPA_0007"
	ErrCodeRentPaymentAlreadyExists         ErrorCode = "RPA_0008"
	ErrCodeRentPaymentNotFound              ErrorCode = "RPA_0009"
	ErrCodeRentPaymentContractLookupError   ErrorCode = "RPA_0010"
	ErrCodeRentPaymentPeriodAlreadyPaid     ErrorCode = "RPA_0011"
	ErrCodeRentPaymentPeriodOutsideContract ErrorCode = "RPA_0012"
)
