apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ingress.yaml

  - mysql/pvc.yaml
  - mysql/service.yaml
  - mysql/statefulset.yaml

  - backend/configmap.yaml
  - backend/deployment.yaml
  - backend/service.yaml

  - frontend/configmap.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml