apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: rent-manager
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: CHANGE_ME
  MYSQL_DATABASE: rent_manager
  MYSQL_USER: rent_manager
  MYSQL_PASSWORD: CHANGE_ME